// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $AboutSection from "./islands/AboutSection.tsx";
import * as $DarkModeButton from "./islands/DarkModeButton.tsx";
import * as $Projects from "./islands/Projects.tsx";
import * as $TechCarousel from "./islands/TechCarousel.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AboutSection.tsx": $AboutSection,
    "./islands/DarkModeButton.tsx": $DarkModeButton,
    "./islands/Projects.tsx": $Projects,
    "./islands/TechCarousel.tsx": $TechCarousel,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
